name: BuildViaZephyrAction

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: "0 19 * * 1-5"
jobs:
  installZephyrAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        
      - name: InstallWestWorkspace
        run: |
          #pip3 install west
          #cd ${{github.workspace}}
          #cd ..

          #west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.1.1 /home/runner/work
          #cd /home/runner/work
          #west update
          #pip3 install -r zephyr/scripts/requirements-base.txt
          #west init
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.1.1
          west update
          
          #sudo apt install --no-install-recommends cmake ninja-build
          #source ./zephyr/zephyr-env.sh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: repototest

      - name: BuildTargets
        working-directory: repototest
        run: |
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.15.1/
          west build --pristine -b qemu_x86
          #next line gives error 'no module named 'cbor2''
          pip install cbor2
          west build --pristine -b thingy91_nrf9160_ns

      - name: RunTwister
        working-directory: repototest
        run: |
          #pip install tabulate
          #pip install ply
          #next line necessary to build for native_posix
          sudo apt install gcc-multilib
          /home/runner/work/zephyr/scripts/twister -v --integration  -T ./

